id: api-appveyor

info:
  name: AppVeyor API Test
  author: dwisiswant0
  reference: https://www.appveyor.com/docs/api/
  severity: info
  tags: token-spray,appveyor

self-contained: true
requests:
  - method: GET
    path:
      - "https://ci.appveyor.com/api/roles"
    headers:
      Content-Type: application/json
      Authorization: Bearer {{token}}

    matchers:
      - type: word
        part: body
        words:
          - "Authorization required"
        negative: true
