id: accueil-wampserver

info:
  name: Accueil WAMPSERVER
  author: tess
  severity: low
  metadata:
    verified: true
    shodan-query: http.title:"Accueil WAMPSERVER"
  tags: exposure,accueil

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Accueil WAMPSERVER"
          - "Configuration Serveur"

      - type: status
        status:
          - 200
