id: airflow-configuration-exposure

info:
  name: Apache Airflow Configuration Exposure
  author: Ice3man
  severity: medium

requests:
  - method: GET
    path:
      - '{{BaseURL}}/airflow.cfg'
    matchers:
      - type: word
        words:
          - '[core]'
          - '[api]'
        condition: and