id: amazon-docker-config-disclosure

info:
  name: Dockerrun AWS Configuration Exposure
  author: Ice3man
  severity: medium

requests:
  - method: GET
    path:
      - '{{BaseURL}}/Dockerrun.aws.json'
    matchers:
      - type: word
        words:
          - 'AWSEBDockerrunVersion'
          - 'containerDefinitions'
        condition: and