id: ansible-config-disclosure

info:
  name: Ansible Configuration Exposure
  author: pd-team
  severity: medium
  tags: config,exposures

requests:
  - method: GET
    path:
      - '{{BaseURL}}/ansible.cfg'
    matchers:
      - type: word
        words:
          - '[defaults]'
          - '[inventory]'
        condition: and