id: appsec-yml-disclosure

info:
  name: Appsec Yml Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json
  tags: exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/appspec.yml"
      - "{{BaseURL}}/appspec.yaml"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "\"version\""
          - "\"os\""
          - "\"files\""
          - "\"permissions\""
          - "\"hooks\""
          - "\"BeforeInstall\""
          - "\"ApplicationStart\""
        part: body
      - type: word
        words:
          - "application/yaml"
        part: header
      - type: status
        status:
          - 200
