id: cloud-config

info:
  name: Cloud Config File Exposure
  author: Hardik-Solanki
  severity: medium
  metadata:
    verified: true
    github-query: path:cloud-config.txt
  tags: cloud,files,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}/cloud-config.txt'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'ssh_authorized_keys:'
          - 'packages:'
        condition: and

      - type: status
        status:
          - 200
