id: config-rb

info:
  name: Config Ruby File Disclosure
  author: DhiyaneshDK
  severity: medium
  metadata:
    verified: true
    shodan-query: html:"config.rb"
  tags: ruby,devops,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config.rb"
      - "{BaseURL}}/.chef/config.rb"
      - "{{BaseURL}}/assets/config.rb"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'http_path'
          - 'css_dir'

      - type: word
        part: header
        words:
          - 'application/ruby'

      - type: status
        status:
          - 200
