id: config-json

info:
  name: Config File Exposure
  author: geeknik
  severity: high
  metadata:
    verified: true
    github-query: filename:config.json
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/default.json"
      - "{{BaseURL}}/config.json"
      - "{{BaseURL}}/config/config.json"
      - "{{BaseURL}}/credentials/config.json"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"api_keys":'
          - '"accessKey":'
          - '"secretKey":'
        condition: or

      - type: status
        status:
          - 200
