id: database-credentials

info:
  name: Database Credentials File Exposure
  author: Hardik-Solanki
  severity: high
  metadata:
    verified: true
    github-query: filename:database_credentials.inc
  reference:
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
  tags: exposure,database,config,files

requests:
  - method: GET
    path:
      - "{{BaseURL}}/database_credentials.inc"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '$DATABASE_USER'
          - '$DATABASE_PASS'
        condition: and

      - type: status
        status:
          - 200
