id: dbeaver-credentials

info:
  name: DBeaver Credential Exposure
  author: geeknik
  severity: info
  tags: exposure,dbeaver

# to decode the above file, run this:
# openssl aes-128-cbc -d -K "babb4a9f774ab853c96c2d653dfe544a" -iv 00000000000000000000000000000000 -in credentials-config.json | dd bs=1 skip=16 2>/dev/null


requests:
  - method: GET
    path:
      - "{{BaseURL}}/.dbeaver/credentials-config.json"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "application/octet-stream"
        part: header
