id: detect-drone-config

info:
  name: Detect Drone Configuration
  author: geeknik
  description: Drone is a Container-Native, Continuous Delivery Platform -- https://github.com/drone/drone
  severity: high
  tags: config,exposure,auth

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.drone.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "services:"
          - "environment:"
          - "commands:"
        condition: and
      - type: status
        status:
          - 200
