id: django-framework-exceptions-http

info:
  name: Exposed django variables
  author: nobody
  severity: low
  description: Detects suspicious Django web application framework exceptions that could indicate exploitation attempts  
  reference:
    - https://docs.djangoproject.com/en/1.11/ref/exceptions/
    - https://docs.djangoproject.com/en/1.11/topics/logging/#django-security
    - https://github.com/projectdiscovery/nuclei-templates/blob/master/file/logs/django-framework-exceptions.yaml
  tags: config,exposure,django

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'seeing this error because you have <code>DEBUG = True</code>'
          - 'SuspiciousOperation'
          - 'DisallowedHost'
          - 'DisallowedModelAdminLookup'
          - 'DisallowedModelAdminToField'
          - 'DisallowedRedirect'
          - 'InvalidSessionKey'
          - 'RequestDataTooBig'
          - 'SuspiciousFileOperation'
          - 'SuspiciousMultipartForm'
          - 'SuspiciousSession'
          - 'TooManyFieldsSent'
          - 'PermissionDenied'
        condition: or

      - type: status
        status:
          - 400

      - type: word
        part: header
        words:
          - "text/html"
