id: editor-exposure

info:
  name: Editor Config Exposure
  author: DhiyaneshDk
  severity: low
  metadata:
    verified: true
    shodan-query: html:"editorconfig"
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.editorconfig"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "= true"
          - "space"

      - type: status
        status:
          - 200
