id: exposed-bitkeeper

info:
  name: Exposed BitKeeper Directory
  author: daffainfo
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/BitKeeper/etc/config"

    matchers:
      - type: word
        words:
          - "logging"
          - "email"
          - "description"
        condition: and

      - type: status
        status:
          - 200
