id: exposed-darcs

info:
  name: Exposed Darcs Directory
  author: daffainfo
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_darcs/prefs/binaries"

    matchers:
      - type: word
        words:
          - "Binary file regexps"

      - type: status
        status:
          - 200
