id: exposed-bzr

info:
  name: Exposed BZR Directory
  author: daffainfo
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.bzr/branch/branch.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "parent_location"
          - "push_location"
        condition: and

      - type: status
        status:
          - 200
