id: exposed-hg

info:
  name: Exposed HG Directory
  author: daffainfo
  severity: medium

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.hg/hgrc"
      
    matchers:
      - type: word
        words:
          - "[paths]"
          - "default"
        condition: and
