id: ftp-credentials-exposure

info:
  name: FTP credentials exposure
  author: pikpikcu
  severity: medium
  tags: config,ftp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ftpsync.settings"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "host"
          - "username"
          - "password"
        part: body
        condtion: and

      - type: status
        status:
          - 200