id: git-credentials-disclosure

info:
  name: Git Credentials Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/git-credentials-disclosure.json
  tags: exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.git-credentials"
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "https?://[\\d\\w\\{\\}\\.%]+(?:|@)[\\d\\w\\{\\}\\.]+:[\\d\\w\\{\\}\\.]+(?:|@)[\\d\\w\\{\\}\\.\\?!~#@]+"
        part: body
      - type: word
        words:
          - "Content-Type: text/html"
        part: header
      - type: status
        status:
          - 200
