id: gruntfile

info:
  name: gruntfile exposure
  author: sbani
  severity: info
  reference: https://gruntjs.com/sample-gruntfile
  tags: config,exposure

requests:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/Gruntfile.js"
      - "{{BaseURL}}/Gruntfile.coffee"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "module.exports"
        part: body

      - type: status
        status:
          - 200
