id: javascript-env

info:
  name: JavaScript Environment Config
  author: pdp
  severity: low
  description: Detects common JavaScript environment configuration files.
  tags: javascript,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/env.js"
      - "{{BaseURL}}/env.development.js"
      - "{{BaseURL}}/env.production.js"
      - "{{BaseURL}}/env.test.js"
      - "{{BaseURL}}/env.dev.js"
      - "{{BaseURL}}/env.prod.js"

    matchers-condition: and
    matchers:

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "application/javascript"

      - type: word
        part: body
        words:
          - "module.exports"
          - "const audience"
          - "const domain"
        condition: or
