id: kubernetes-kustomization-disclosure

info:
  name: Kubernetes Kustomization Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/kubernetes-kustomization-disclosure.json
  tags: exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/kustomization.yml"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(?m)^\\s*apiVersion\\s*:\\s*kustomize\\.config"
          - "(?mi)^\\s*kind\\s*:\\s*Kustomization"
          - "(?m)^\\scommonLabels\\s*:"
          - "(?m)^\\sresources\\s*:"
          - "(?m)^\\snamespace\\s*:"
        part: body

      - type: word
        words:
          - "Content-Type: application/yaml"
        part: header
      - type: status
        status:
          - 200
