id: kyan-network-monitor-disclosure

info:
  name: Kyan network monitoring device account and password disclosure
  author: pikpikcu
  severity: medium
  reference: |
    - https://mp.weixin.qq.com/s/6phWjDrGG0pCpGuCdLusIg
  tags: kyan,disclosure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/hosts"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "UserName="
          - "Password="
        condition: and

      - type: status
        status:
          - 200
