id: laravel-env

info:
  name: Laravel .env file
  author: pxmme1337 & dwisiswant0 & geeknik & emenalf
  severity: medium

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.env"
      - "{{BaseURL}}/.env.dev.local"
      - "{{BaseURL}}/.env.development.local"
      - "{{BaseURL}}/.env.prod.local"
      - "{{BaseURL}}/.env.production.local"
      - "{{BaseURL}}/.env.local"
      - "{{BaseURL}}/.env.example"
      - "{{BaseURL}}/.env.stage"
      - "{{BaseURL}}/.env.live"
      - "{{BaseURL}}/.env_1"
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(NAME|ENV|KEY|DEBUG|URL|PASSWORD)"
      - type: status
        status:
          - 200
