id: oracle-cgi-printenv

info:
  name: Oracle CGI printenv Information Disclosure
  author: DhiyaneshDk
  severity: medium
  reference:
    - https://github.com/ilmila/J2EEScan/blob/master/src/main/java/burp/j2ee/issues/impl/OracleCGIPrintEnv.java
  tags: oracle,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/printenv"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DOCUMENT_ROOT"
        part: body

      - type: word
        words:
          - "text/plain"

        part: header
      - type: status
        status:
          - 200
