id: ovpn-config-exposed

info:
  name: OVPN Config Download
  author: tess
  severity: low
  metadata:
    verified: "true"
    shodan-dork: http.title:"OVPN Config Download"
  tags: ovpn,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}/'

    matchers-condition: and
    matchers:

      - type: word
        words:
          - 'OVPN Config Download'
          - 'Config List'
        part: body
        condition: and

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
