id: parameters-config

info:
  name: Parameters Yaml File Disclosure
  author: DhiyaneshDK
  severity: High
  reference: 
  metadata:
    shodan-query: html:"parameters.yml"
  tags: misconfig,cloud,devops

requests:
  - method: GET
    path:
      - "{{BaseURL}}/parameters.yml"
      - "{{BaseURL}}/app/config/parameters.yml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'database_user'
          - 'database_password'

      - type: status
        status:
          - 200
