id: pendinginstallvzw-web-configuration

info:
  name: PendingInstallVZW - Web Page Configuration
  author: tess
  severity: low
  metadata:
    verified: true
    shodan-query: http.title:"PendingInstallVZW - Web Page Configuration"
  tags: exposure,pendinginstallvzw

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'PendingInstallVZW - Web Page Configuration'
          - 'Overview'
          - 'WWAN Connection:'
          - 'WWAN IP Address:'
        condition: and

      - type: status
        status:
          - 200
