id: phpstan-config

info:
  name: PHPStan Configuration Exposure
  author: DhiyaneshDK
  severity: low
  metadata:
    verified: true
    shodan-query: html:"phpstan.neon"
  tags: devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phpstan.neon"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'parameters:'
        condition: and

      - type: status
        status:
          - 200
