id: pipfile-config

info:
  name: Pipfile Configuration Exposure
  author: DhiyaneshDK
  severity: low
  metadata:
    verified: true
    shodan-query: html:"Pipfile"
  tags: exposure,pip,devops,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/Pipfile"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[[source]]'
          - '[packages]'
        condition: and

      - type: status
        status:
          - 200
