id: pre-commit-config

info:
  name: Pre Commit Configuration File Exposure
  author: DhiyaneshDk
  severity: low
  metadata:
    verified: true
    shodan-query: html:"pre-commit-config.yaml"
  tags: exposure,devops,config,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.pre-commit-config.yaml"
      - "{{BaseURL}}/pre-commit-config.yaml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "repos:"
          - "hooks:"
          - "rev:"

      - type: status
        status:
          - 200
