id: procfile-config

info:
  name: Procfile Configuration File Exposure
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    shodan-query: html:"Procfile"
  tags: devops,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/Procfile"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'web:'
        condition: and

      - type: status
        status:
          - 200
