id: prometheus-targets-endpoint

info:
  name: Exposure of sensitive operational information via Prometheus targets API endpoint
  author: geeknik
  description: The targets endpoint exposes services belonging to the infrastructure, including their roles and labels. In addition to showing the target machine addresses, the endpoint also exposes metadata labels that are added by the target provider. These labels are intended to contain non-sensitive values, like the name of the server or its description, but various cloud platforms may automatically expose sensitive data in these labels, oftentimes without the developer’s knowledge.
  reference: https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  severity: high
  tags: prometheus,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/targets"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
        words:
          - "Endpoint"
          - "State"
          - "Labels"
        condition: and
