id: pubspec-config

info:
  name: Pubspec YAML Configuration File Exposure
  author: DhiyaneshDk
  severity: low
  metadata:
    verified: true
    shodan-query: html:"pubspec.yaml"
  tags: exposure,devops,pubsec,config,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/pubspec.yaml"
      - "{{BaseURL}}/assets/pubspec.yaml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "version:"
          - "environment:"
          - "dependencies:"

      - type: status
        status:
          - 200
