id: pyproject-toml

info:
  name: Pyproject.toml Configuration Exposure
  author: DhiyaneshDK
  severity: low
  metadata:
    verified: true
    shodan-query: html:"pyproject.toml"
  tags: exposure,pip,devops,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/pyproject.toml"

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "[tool.black]"
          - "exclude ="
        condition: or

      - type: word
        part: body
        words:
          - "[tool.poetry]"
          - "name ="
        condition: or
