id: rails-database-config

info:
  name: Ruby-on-Rails Database Configuration Exposure
  author: pdteam & geeknik
  severity: low
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "application/octet-stream"
      - type: word
        words:
          - "adapter:"
          - "database:"
        condition: and
        part: body
