id: sftp-credentials-exposure

info:
  name: SFTP credentials exposure
  author: sheikhrishad
  severity: medium
  tags: config,ftp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/sftp-config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "file_permissions"
          - "extra_list_connections"
        condition: and

      - type: status
        status:
          - 200