id: ssh-secret

info:
  name: SSH Secret
  author: pikpikcu
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.ssh/id_rsa"
      - "{{BaseURL}}/.ssh/known_hosts"
      - "{{BaseURL}}/.ssh/id_rsa.pub"
      - "{{BaseURL}}/.ssh/authorized_keys"
      - "{{BaseURL}}/_/.ssh/authorized_keys"
      - "{{BaseURL}}/.ssh/known_hosts.old"

    matchers-condition: and
    matchers:

      - type: word
        words:
         - "Content-Type: text/plain"
        part: header

      - type: word
        words:
         - "-----BEGIN RSA PRIVATE KEY-----"
         - "ssh-rsa"
        part: body

      - type: status
        status:
          - 200
