id: symfony-profiler

info:
  name: Symfony Profiler
  author: pdteam
  severity: high
  tags: config,exposure,symfony

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/app_dev.php/_profiler/empty/search/results?limit=10"

    matchers:
      - type: word
        part: body
        words:
          - "Symfony Profiler"