id: yii-debugger

info:
  name: View Yii Debugger Information
  author: geeknik
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/debug/default/view.html"
      - "{{BaseURL}}/debug/default/view"
      - "{{BaseURL}}/frontend/web/debug/default/view"
      - "{{BaseURL}}/web/debug/default/view"
      - "{{BaseURL}}/sapi/debug/default/view"

    redirects: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "<title>Yii Debugger</title>"
          - "Status"
          - "Route"
          - "Log"
          - "Time"
          - "Memory"
          - "DB"
        condition: and
