xid: configuration-files-detection
info:
  name: Sensitive Configuration Files Detection
  author: j33n1k4
  severity: medium
  description: directory listing of sensitive files
  reference: https://www.exploit-db.com/ghdb/7014
  tags: config,files,directory-listing
requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/"
    matchers:
      - type: word
        words:
          - "Index of"
          - "/config"
      - type: status
        status:
          - 200    
