id: web-config
info:
  name: web config file
  author: Yash Anand @yashanand155
  severity: medium
requests:
  - method: GET
    path:
      - '{{BaseURL}}/web.config'
    matchers:
      - type: word
        words:
          - <configuration>
