id: openapi

info:
  name: OpenAPI
  author: pdteam,ynnirc
  severity: info
  tags: exposure,api

requests:
  - method: GET
    path:
      - "{{BaseURL}}/openapi.json"
      - "{{BaseURL}}/swagger.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - application/openapi+json
          - application/json
        part: header

      - type: word
        words:
          - openapi
          - paths
        condition: and

      - type: status
        status:
          - 200
