id: s3cmd-config

info:
  name: S3CMD Configuration Disclosure
  author: Ice3man
  severity: info
  tags: amazon,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/s3cmd.ini"

    matchers:
      - type: word
        part: body
        words:
          - '[default]'
          - 'access_key'
        condition: and