id: .idea-folder-with.sensitive-files

info:
  name: Reachable or public .idea-Folder files containing sensitive data
  author: martincodes-de
  severity: high
  description: Searches for .idea-Folder by querying the /.idea and a few other files with sensitive data endpoints
  tags: phpstorm, jetbrains, .idea, sensitive data

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.idea/httpRequests/http-requests-log.http"
      - "{{BaseURL}}/.idea/deployment.xml"
      - "{{BaseURL}}/.idea/workspace.xml"
    matchers:
      - type: status
          status:
            - 200