id: appsettings-file-disclosure

info:
  name: Application Setting file disclosure
  author: DhiyaneshDK, tess
  severity: high
  description: appsetting.json file discloses the DB connection strings containing sensitive information.
  reference: https://twitter.com/hacker_/status/1518003548855930882?s=20&t=BVauK0yUjVl5yL7rwy0Eag
  tags: exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/appsettings.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ConnectionStrings"
        condition: and

      - type: word
        words:
          - "application/json"
        part: header

      - type: status
        status:
          - 200
