id: bitbucket-pipelines

info:
  name: BitBucket Piplelines Configuration Exposure
  author: DhiyaneshDK
  severity: medium
  metadata:
    verified: true
    shodan-query: html:"bitbucket-pipelines.yml"
  tags: bitbucket,devops,exposure,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/bitbucket-pipelines.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'pipelines'
          - 'step'
        condition: and

      - type: status
        status:
          - 200
