id: environment-rb

info:
  name: Environment Ruby File Disclosure
  author: DhiyaneshDK
  severity: medium
  metadata:
    verified: true
    google-query: intitle:"index of" "environment.rb"
  tags: ruby,devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/environment.rb"
      - "{{BaseURL}}/config/environment.rb"
      - "{BaseURL}}/redmine/config/environment.rb"


    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'File.expand_path'

      - type: word
        part: header
        words:
          - 'application/x-ruby'

      - type: status
        status:
          - 200
