id: redmine-config

info:
  name: Redmine Configuration
  author: DhiyaneshDK
  severity: high
  reference: https://www.exploit-db.com/ghdb/5803
  metadata:
    google-dork: intitle:"index of" configuration.yml
  tags: misconfig,redmine,devops

requests:
  - method: GET
    path:
      - "{{BaseURL}}/configuration.yml"
      - "{{BaseURL}}/config/configuration.yml"
      - "{{BaseURL}}/redmine/config/configuration.yml"
      - "{{BaseURL}}/configuration.yml.example"
      - "{{BaseURL}}/config/configuration.yml.example"
      - "{{BaseURL}}/redmine/config/configuration.yml.example"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'user_name'
          - 'password'

      - type: status
        status:
          - 200
