id: symfony-security

info:
  name: Symfony security.yml File Disclosure
  author: DhiyaneshDK
  severity: low
  metadata:
    google-dork: intitle:"index of "security.yml"
  tags: symfony,devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/security.yml"
      - "{{BaseURL}}/config/security.yml
      - "{{BaseURL}}/app/config/security.yml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'security:'
          - 'providers:'

      - type: status
        status:
          - 200
