id: xampp-environment-variable

info:
  name: XAMPP Environment Variable Exposure
  author: melbadry9, DhiyaneshDK
  severity: low
  tags: exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/printenv.pl"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<TITLE>Environment Variables</TITLE>"

        condition: and

      - type: word
        words:
          - "text/html"
        part: header

      - type: status
        status:
          - 200
