id: cors-misconfig

info:
  name: Cross-Origin Resource Sharing Misconfiguration
  author: G4L1T0 and @convisoappsec 
  severity: info
  tags: cors

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
        Origin: https://www.convisoappsec.com
    matchers:
      - type: word
        part: header
        words:
          - "Access-Control-Allow-Origin: https://www.convisoappsec.com"
          - "Access-Control-Allow-Origin: *"
        condition: or

