id: cloud-config

info:
  name: Cloud Config Yaml File Disclosure
  author: DhiyaneshDK
  severity: Medium
  reference: https://www.exploit-db.com/ghdb/7959
  metadata:
    shodan-query: html:"cloud-config.yml"
  tags: misconfig,cloud,devops

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cloud-config.yml "
      - "{{BaseURL}}/core-cloud-config.yml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'ssh_authorized_keys'
          - 'hostname'

      - type: status
        status:
          - 200
