id: iotawatt-configuration-app
info:
  name: IoTaWatt-Configuration-app
  author: pussycat0x
  severity: high
  description: unauthenticated IoTaWatt energy monitor leads to upload to any of several third-party energy websites/database
  metadata:
    fofa-dork: 'app="IoTaWatt-Configuration-app"'
  tags: iot
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers-condition: and
    part: body
    matchers:
      - type: word
        words:
          - '<h3>Configure IoTaWatt Device</h3>'
      - type: status
        status:
          - 200