id: misconfigured-docker

info:
  name: Misconfigured Docker on Default Port
  author: dhiyaneshDK
  severity: Critical

requests:
  - method: GET
    path:
      - "{{BaseURL}}/images/json"
      - "{{BaseURL}}:2375/images/json"
      - "{{BaseURL}}:2376/images/json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Containers'

      - type: status
        status:
          - 200
