id: Oracle

info:
  name: Oracle E-Business Login Panel Registration Accessible
  author: tess
  severity: critical
  description: Oracle E-Business Login Panel Registration Accessible.
  reference:
    - https://twitter.com/GodfatherOrwa/status/1514720677173026816
    - https://orwaatyat.medium.com/my-new-discovery-in-oracle-e-business-login-panel-that-allowed-to-access-for-all-employees-ed0ec4cad7ac
  tags: oracle

requests:
  - method: GET
    path:
      - '{{BaseURL}}/OA_HTML/ibeCAcpSSOReg.jsp'

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'Registration'
          - 'Register as individual'
          - '<!-- ibeCZzpRuntimeIncl.jsp end -->'
