id: jira-misconfiguration-workflow

info:
        name: Jira misconfiguration workflow
        author: micha3lb3n

variables:
        jira_detect: technologies/jira-detect.yaml
        jira_signup: security-misconfiguration/jira-service-desk-signup.yaml
        jira_projects: security-misconfiguration/jira-unauthenticated-projects.yaml
        jira_dashboard: security-misconfiguration/jira-unauthenticated-dashboards.yaml
        jira_filters: security-misconfiguration/jira-unauthenticated-popular-filters.yaml
        jira_user_picker: security-misconfiguration/jira-unauthenticated-user-picker.yaml

logic:
        |
        if jira_detect(){
                jira_signup()
                jira_projects()
                jira_dashboard()
                jira_filters()
                jira_user_picker()
        }
