id: dockercfg

info:
  name: Detect .dockercfg
  author: geeknik
  severity: high
  description: Docker registry authentication data
  tags: docker,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.dockercfg"
      - "{{BaseURL}}/.docker/config.json"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - '"email":'
          - '"auth":'
        condition: and

      - type: status
        status:
          - 200