id: owncloud-config

info:
  name: owncloud config Disclosure
  author: Mahendra Purbia (Mah3Sec_)
  severity: Low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/owncloud/config"
     
    matchers:
      - type: word
        words:
          - "Apache"
          - "Index"
        part: body
