id: amp-application-portal

info:
  name: AMP - Application Management Panel
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    shodan-query: title:"AMP - Application Management Panel"
  tags: panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "text/html"
      - type: word
        words:
          - "<title>AMP - Application Management Panel</title>"
