id: esphome-panel

info:
  name: ESPHome Panel - Detect
  author: fabaff
  severity: info
  description: ESPHome panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: tech,panel,esphome,iot

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<title>Dashboard - ESPHome</title>"

      - type: word
        part: body
        words:
          - "</esphome-main>"

      - type: status
        status:
          - 200
