id: saltStack-config-panel

info:
  name: SaltStack Config Panel
  author: pussycat0x
  severity: info
  description: saltStack config panel was detected.
  metadata:
    verified: true
    shodan-query: title:"SaltStack Config"
  tags: panel,vmware,login

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "SaltStack Config"

      - type: status
        status:
          - 200