id: sonic-wall-application

info:
  name: Sonic Wall Appliance Management Console
  author: DhiyaneshDk,Tess
  severity: info
  metadata:
    verified: true
    fofa-query: title:"Appliance Management Console Login"
  tags: sonicwall,login

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login.do"

    matchers:
      - type: word
        words:
          - '<title>Appliance Management Console Login</title>'

      - type: status
        status:
          - 200
