name: Manual Sync with UpStream

on:
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    name: Fetch Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: main
          token: ${{ github.token }}
          
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add upstream "ttps://github.com/projectdiscovery/nuclei-templates.git"
          
      - name: Fetch and merge
        id: fetch-merge
        run: |
          git fetch upstream
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
