on:
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    name: Fetch Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: main
          token: ${{ github.token }}
          
      - name: Configure git
        run: |
          git config --global user.name "aidenpearce001"
          git remote add upstream git://github.com/projectdiscovery/nuclei-templates.git
          
      - name: Fetch and merge
        id: fetch-merge
        run: |
          git fetch upstream
          
          git checkout main
          git merge upstream/main

          git push origin main
