# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    name: Fetch Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: aidenpearce001/nuclei-templates
          token: ${{ github.token }}
      - name: Configure git
        run: |
          git config --global user.name "aidenpearce001"
          git config --global user.email "noreply@myemail.com"
          git remote add upstream https://github.com/projectdiscovery/nuclei-templates.git
        shell: bash
      - name: Fetch and merge
        id: fetch-merge
        run: |
          git fetch upstream
          git checkout main
          lines=$( git diff main..upstream/main -- . ':(exclude).github/**' | wc -l )
          echo "Number of detected line changes: $lines"
          if [ $lines -gt 0 ]; then
            git merge upstream/main
            git push
          fi
        shell: bash
