name: Sync Fork
on:
  workflow_dispatch 
  
jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch upstream
      uses: actions/checkout@v2
      with:
        repository: projectdiscovery/nuclei-templates
        ref: main
    - name: Merge upstream
      run: |
          git checkout main
          git fetch --all
          git rebase upstream/main
          git merge upstream/main
