id: springboot-autoconfig
info:
  name: Detect Springboot autoconfig Actuator
  author: pussycat0x
  severity: low
  description: Displays an auto-configuration report showing all auto-configuration candidates and the reason why they 'were' or 'were not' applied.
  tags: springboot,disclosure
requests:
  - method: GET
    path:
      - "{{BaseURL}}/autoconfig"
      - "{{BaseURL}}/actuator/autoconfig"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "positiveMatches"
          - "AuditAutoConfiguration#auditListener"
          - "EndpointAutoConfiguration#beansEndpoint"
          - "condition"
        condition: and
      - type: status
        status:
          - 200
      - type: word
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
        condition: or
        part: header