id: bigip-config-utility

info:
  name: BIG-IP Configuration Utility detected
  author: dwisiswant0
  severity: informative

requests:
  - method: GET
    path:
      - "{{BaseURL}}/tmui/login.jsp"
      - "{{BaseURL}}/tmui/tmui/login/welcome.jsp"
    matchers:
      - type: word
        words:
          - "Welcome to the BIG-IP"
          - "Configuration Utility"
          - "You don't have permission to access the requested object"
        condition: or
        part: body
  - method: GET
    path:
      - "{{BaseURL}}/mgmt/tm/sys/management-ip"
    matchers:
      - type: word
        words:
          - "WWW-Authenticate: Basic realm"
          - "Enterprise Manager"
        condition: or
        part: header
      - type: word
        words:
          - "check your user-id and password and try again"
        part: header