id: extreme-netconfig-ui
info:
  name: Extreme NetConfig UI
  author: pussycat0x
  severity: info
  metadata:
    shodan-dork: 'http.title:"Extreme NetConfig UI"'
  tags: login,tech
requests:
  - method: GET
    path:
      - "{{BaseURL}}/index.php5"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Extreme NetConfig UI</title>'
        condition: and
        part: body
      - type: status
        status:
          - 200