id: samsung-smarttv-debug-config
info:
  name: Samsung SmartTV Debug Config
  author: pussycat0x
  severity: info
  metadata:
    shodan-query: title:"Debug Config"
  tags: Samsung,tech
requests:
  - method: GET
    path:
      - '{{BaseURL}}'
      - '{{BaseURL}}:8001'
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Debug Config</title>'
      - type: status
        status:
          - 200